/**
 * Student model — PERMISSIVE by design.
 * Only studentId and branch are required (both auto-generated by the API).
 * Every field a user fills on the form is optional at the schema level.
 * The API layer enforces only firstName (the single UX-visible required field).
 */
import mongoose, { Schema, Document } from 'mongoose';

export interface IStudent extends Document {
  studentId: string;
  userId?: mongoose.Types.ObjectId;
  branch?: mongoose.Types.ObjectId;
  firstName: string;
  lastName?: string;
  email?: string;
  phone?: string;
  dateOfBirth?: Date;
  admissionDate?: Date;
  gender?: string;
  cnic?: string;
  address?: string;
  city?: string;
  class?: mongoose.Types.ObjectId;
  section?: string;
  rollNumber?: string;
  fatherName?: string;
  motherName?: string;
  scholarshipType?: string;
  scholarshipPercentage?: number;
  notes?: string;
  guardians?: Array<{ name?: string; phone?: string; relationship?: string }>;
  enrollments?: Array<{
    course?: mongoose.Types.ObjectId;
    batch?: mongoose.Types.ObjectId;
    status?: string;
    enrollDate?: Date;
  }>;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const StudentSchema = new Schema<IStudent>(
  {
    studentId:  { type: String, unique: true, default: () => `STU-${Date.now()}-${Math.floor(100 + Math.random() * 900)}` },
    userId:     { type: Schema.Types.ObjectId, ref: 'User' },
    branch:     { type: Schema.Types.ObjectId, ref: 'Branch' },
    firstName:  { type: String, required: true },
    lastName:   { type: String, default: '' },
    email:      { type: String, lowercase: true },
    phone:      { type: String },
    dateOfBirth:    { type: Date },
    admissionDate:  { type: Date, default: Date.now },
    gender:     { type: String },
    cnic:       { type: String },
    address:    { type: String },
    city:       { type: String },
    class:      { type: Schema.Types.ObjectId, ref: 'Class' },
    section:    { type: String },
    rollNumber: { type: String },
    fatherName: { type: String },
    motherName: { type: String },
    scholarshipType:       { type: String, default: 'none' },
    scholarshipPercentage: { type: Number, default: 0 },
    notes:      { type: String },
    guardians:  [{ name: String, phone: String, relationship: String }],
    enrollments: [{
      course:     { type: Schema.Types.ObjectId, ref: 'Course' },
      batch:      { type: Schema.Types.ObjectId, ref: 'Batch' },
      status:     { type: String, default: 'enrolled' },
      enrollDate: { type: Date, default: Date.now },
    }],
    isActive: { type: Boolean, default: true },
  },
  { timestamps: true, strict: false }   // strict:false = extra fields never throw
);

// Ensure unique index on studentId only
StudentSchema.index({ studentId: 1 }, { unique: true });

export const Student = mongoose.models.Student || mongoose.model<IStudent>('Student', StudentSchema);
